name: Run tests

on:
  # Triggers the workflow on push or pull request events for the "main" & "dev "branch
  push:
    branches: 
      - main
      - dev
    paths-ignore:
      - '*.md'
      - '.github/**'
      - 'docs/reports/**'

  pull_request:
    branches:
      - main
      - dev
    paths-ignore:
      - '*.md'
      - '.github/**'
      - 'docs/reports/**'

  # Allows for manually running this workflow from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "test"
  test:
    name: Test toolbox code
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - name: Check out repo
        uses: actions/checkout@v4
      
      - name: Set up MATLAB
        uses: matlab-actions/setup-matlab@v2
        with:
          products: Image_Processing_Toolbox

      # Check for MATLAB code issues in the project.
      - name: Check for MATLAB code issues
        uses: matlab-actions/run-command@v2
        if: always()
        with:
          command: addpath(genpath("tools")), codecheckToolbox()
      
      # Upload code issues report
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          # Path to SARIF file relative to the root of the repository
          sarif_file: docs/reports/code_issues.sarif
          
      # Run all tests in the project.
      - name: Run tests
        uses: matlab-actions/run-command@v2
        if: always()
        with:
          command: addpath(genpath("tools")), testToolbox()

      # Commit updated SVG badges for the issues and tests (if changed)
      - name: Commit svg badges if updated
        if: always()
        continue-on-error: true
        run: |
          git config user.name "${{ github.workflow }} by ${{ github.actor }}"
          git config user.email "<>"
          git fetch

          if [[ $(git add .github/badges/* --dry-run | wc -l) -gt 0 ]]; then
            git add .github/badges/*
            git commit -m "Update code issues and tests badges"
            git push -f
          else
            echo "Nothing to commit"
          fi

      - name: Upload code coverage report to Codecov
        uses: codecov/codecov-action@v4
        if: always()
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: docs/reports/codecoverage.xml
          
      # Publish test results
      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: "docs/reports/test-results.xml"
          
      # Save the contents of the reports directory as an artifact
      - name: Save reports directory
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: docs/reports
