name: Test code

on:
  push:
    branches: [ "main", "dev" ]
    paths-ignore:
      - '*md'
      - '.github/**'

  pull_request:
    branches: [ "main", "dev" ]
    paths-ignore:
      - '*md'
      - '.github/**'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-code:
    name: Analyse and test code
    uses: ehennestad/matbox-actions/.github/workflows/test-code-workflow.yml@v1
    with:
      source_directory: code
      tests_directory: tests
      tools_directory: tools
      matlab_release: latest
      matlab_use_cache: true
      matlab_products: >
        Image_Processing_Toolbox
        Statistics_and_Machine_Learning_Toolbox
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
